services:
  - type: web
    name: petty-cash
    env: node
    buildCommand: pnpm install && pnpm run build
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true