create table logs (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  message text not null,
  user_id uuid references auth.users(id)
);
