create table currencies (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  code text not null,
  exchange_rate numeric not null,
  is_default boolean not null default false
);
