create table files (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  path text not null,
  request_id bigint references requests(id)
);
